### ISSUE TITLE
Kovan testnet support request

### ISSUE THREAD

**Issue by jennazenk** [NoteGio/openrelay#34]
Hey, I read on your blog:
>We have no immediate plans to support Kovan or Rinkeby, but are open to doing so if there is significant interest.

Just wanted to show interest from the Melon team for Kovan test net support for our testing needs. This would make the OpenRelay orderbook accessible to Melon Fund Managers on the main net on our next launch scheduled in a few weeks, where users will be incentivized to perform as many trades as possible. 

Here is my email if you're interested in discussing more: jenna@melonport.com

**Comment by AusIV** [comment]
It looks like 0x v2 plans to launch to Kovan before mainnet, so we probably need to support Kovan by then.

**Comment by AusIV** [comment]
We now support 0x v2 on Kovan. At this time we have no plans to add support for the 0x v1 contracts on Kovan, as we're largely focused on the transition to v2.
