### ISSUE TITLE
I have terrible in building open relay in my pc.

### ISSUE THREAD

**Issue by Edison4mobile** [NoteGio/openrelay#55]
If anyone has a chance to help me, I need help to build in windows 10 or ubuntu 16.0.4.
Please help me. Thanks a lot.

**Comment by AusIV** [comment]
At this point we only support Linux builds. It should be possible to build on other environments, but our tooling isn't set up for that.

First, you'll need the [Go Toolchain](https://golang.org/doc/install)

You'll need to check out the OpenRelay git repository into your [Go Path](https://golang.org/doc/code.html#Organization).

From the root of your checkout, you should be able to run `make clean all` to build all of the components.

To run the full stack of OpenRelay, you'll need [Docker](https://www.docker.com/). With Docker installed, you should be able to run:

    docker-compose -f docker-compose-testrpc.yml up

which will build and run all of the OpenRelay services. Once that's running, you can access the OpenRelay ingest service (where you post orders to) at http://localhost:8081 and the OpenRelay search service (where you search for orders) at http://localhost:8082.

It will be running against a ganache-cli test server.

**Comment by AusIV** [comment]
I've created https://github.com/NoteGio/openrelay/issues/56 to track simplifying the build process to a simple Docker command.

**Comment by 751895405** [comment]
issue make all on MAC shows error like:

/usr/local/Cellar/go/1.10.2/libexec/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)

any advice?

**Comment by AusIV** [comment]
As I said earlier, right now we only support Linux builds.

OpenRelay is designed to be run within Docker, and even if you are running Docker on a Mac, it's under a virtualized Linux kernel. That means that if you compile a Mac binary and then pull it into the Docker image it won't run because it's a Mac binary trying to run on Linux.

Now, you could probably get the binaries to compile under Mac by editing the Makefile to remove

    -ldflags '-extldflags "-static"'

From line 4, but the binaries you generate won't run in Docker. 

Another option is to build the binaries in a docker container. I think you should be able to do that with:

    docker run --rm -v "$PWD":/usr/src/github.com/notegio/openrelay -w /usr/src/github.com/notegio/openrelay golang:1.8 make all

That will start a Golang 1.8 docker container, mount in your current directory, and compile all the binaries, which should end up in the same place that they would have if you had built locally.

When I can find time to implement #56 it will put the Go build into a docker container under normal circumstances, which should make it easier for people running on other platforms.

**Comment by Edison4mobile** [comment]
Makefile:94: warning: overriding recipe for target '/home/don/My'
Makefile:9: warning: ignoring old recipe for target '/home/don/My'
Makefile:98: warning: overriding recipe for target '/home/don/My'
Makefile:94: warning: ignoring old recipe for target '/home/don/My'
docker stop `cat /home/don/My Directory/work/relay/openrelay-master/.gopath/src/github.com/notegio/openrelay/tmp/redis.containerid` || true
cat: /home/don/My: Is a directory
cat: Directory/work/relay/openrelay-master/.gopath/src/github.com/notegio/openrelay/tmp/redis.containerid: No such file or directory
"docker stop" requires at least 1 argument(s).
See 'docker stop --help'.

Usage:  docker stop [OPTIONS] CONTAINER [CONTAINER...]

Stop one or more running containers
docker rm `cat /home/don/My Directory/work/relay/openrelay-master/.gopath/src/github.com/notegio/openrelay/tmp/redis.containerid` || true
cat: /home/don/My: Is a directory
cat: Directory/work/relay/openrelay-master/.gopath/src/github.com/notegio/openrelay/tmp/redis.containerid: No such file or directory
"docker rm" requires at least 1 argument(s).
See 'docker rm --help'.

Usage:  docker rm [OPTIONS] CONTAINER [CONTAINER...]

Remove one or more containers
rm /home/don/My Directory/work/relay/openrelay-master/.gopath/src/github.com/notegio/openrelay/tmp/redis.containerid || true
rm: cannot remove '/home/don/My': Is a directory
rm: cannot remove 'Directory/work/relay/openrelay-master/.gopath/src/github.com/notegio/openrelay/tmp/redis.containerid': No such file or directory
docker stop `cat /home/don/My Directory/work/relay/openrelay-master/.gopath/src/github.com/notegio/openrelay/tmp/postgres.containerid` || true
cat: /home/don/My: Is a directory
cat: Directory/work/relay/openrelay-master/.gopath/src/github.com/notegio/openrelay/tmp/postgres.containerid: No such file or directory
"docker stop" requires at least 1 argument(s).
See 'docker stop --help'.

Usage:  docker stop [OPTIONS] CONTAINER [CONTAINER...]

Stop one or more running containers

**Comment by AusIV** [comment]
It looks like our makefile doesn't account for the possibility of spaces in in a filename. I'll push a fix out shortly.

**Comment by AusIV** [comment]
We've updated our docker files to use multistage builds, so now you should just be able to run 

    docker-compose -f docker-compose-testrpc.yml up

And it will take care of the Go builds in that process, so you don't need to worry about having a go environment.

**Comment by AusIV** [comment]
I'm going to close this issue, as I think it should be resolved. Reopen if you have any further issues.

**Comment by Edison4mobile** [comment]
Thanks a lot.
