### ISSUE TITLE
Dockerize the Build Process

### ISSUE THREAD

**Issue by AusIV** [NoteGio/openrelay#56]
We should use Docker's [Multi-stage Builds](https://docs.docker.com/develop/develop-images/multistage-build/#name-your-build-stages) to create our Docker images, I believe that can simplify our instructions to get an environment up and running from:

* Use Linux
* Get the Go Toolchain
* Get Docker
* Run the make command
* Run Docker Compose

to:

* Get Docker
* Run Docker Compose

Allowing us to support development on a wider variety of platforms, and reduce the setup process.

**Comment by chapati23** [comment]
hey @AusIV :)
just tried to get it running on macOs with `docker-compose -f docker-compose-testrpc.yml up` and ran into this error:

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/117495/41352379-a04699d0-6f19-11e8-9bdd-3f33118bc91f.png">

And I don't see the `docker-cfg/ca-certificates.crt` it tries to COPY in [./docker-cfg](https://github.com/NoteGio/openrelay/tree/master/docker-cfg). Did you forget to commit those? Or how do I get those certs?

**Comment by chapati23** [comment]
yeah, it's in `.gitignore` so this can't work currently: https://github.com/NoteGio/openrelay/blob/b60cebe7be6cb86fdd6def551a77ec6e7d479d80/.gitignore

**Comment by AusIV** [comment]
Basically, most of the Docker containers don't have any os files. The ones that need to connect to SSL services need certs to verify connections. Grabbing the host OS' cert file works, but I didn't add that to the Docker build when I switched to multistage builds m

**Comment by chapati23** [comment]
That won't work for macOS unfortunately as there is no accessible root cert bundle.  SSL libraries typically use Apple's Security Framework internally and obtain certificates from Keychain. See https://stackoverflow.com/questions/24675167/ca-certificates-mac-os-x

I've found a workaround, though. If you install `openssl` with homebrew (`brew install openssl`) then it'll put a cert bundle under `/usr/local/etc/openssl/cert.pem`

changing the `docker-cfg` make task to:

```sh
docker-cfg/ca-certificates.crt:
	cp /usr/local/etc/openssl/cert.pem docker-cfg/ca-certificates.crt
```

did the trick for me.
